### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'static' (T_STATIC) in UBLParser.php on line 361

### ISSUE THREAD

**Issue by dpblnt** [ahmeti/ubl-parser-php#1]
```
PHP Parse error:  syntax error, unexpected 'static' (T_STATIC) in UBLParser.php on line 361
```

PHP 7.4.25 (cli)

**Comment by ahmeti** [comment]
Static return type was added in php 8.0 and you are using php 7.4 version. But "self" return type is supported in php7.4. If you want, you can change the return type "static" to "self"

https://github.com/ahmeti/ubl-parser-php/blob/51d4532a302af9e10faebbef269cf12437129361/UBLParser.php#L361

**Comment by dpblnt** [comment]
Yes, I just removed the static and everything works fine.
Thanks
